name: Build Go Project and Create Release
on:
    push:
        branches: [release]

permissions:
    contents: write

jobs:
    build_and_release:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-20.04]

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: "^1.22.1"

            - name: Linux
              if: matrix.os == 'ubuntu-20.04'
              run: |
                  go build -ldflags="-s -w" -o tgpt-linux-amd64
                  GOARCH=386 go build -ldflags="-s -w" -o tgpt-linux-i386
                  GOARCH=arm64 go build -ldflags="-s -w" -o tgpt-linux-arm64
                  GOARCH=arm go build -ldflags="-s -w" -o tgpt-linux-arm

                  GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o tgpt-amd64.exe
                  GOOS=windows GOARCH=arm go build -ldflags="-s -w" -o tgpt-arm.exe
                  GOOS=windows GOARCH=arm64 go build -ldflags="-s -w" -o tgpt-arm64.exe
                  GOOS=windows GOARCH=386 go build -ldflags="-s -w" -o tgpt-i386.exe

                  GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o tgpt-mac-amd64
                  GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o tgpt-mac-arm64

                  GOOS=netbsd GOARCH=amd64 go build -ldflags="-s -w" -o tgpt-netbsd-amd64
                  GOOS=netbsd GOARCH=arm64 go build -ldflags="-s -w" -o tgpt-netbsd-arm64
                  GOOS=netbsd GOARCH=arm go build -ldflags="-s -w" -o tgpt-netbsd-arm
                  GOOS=netbsd GOARCH=386 go build -ldflags="-s -w" -o tgpt-netbsd-i386

                  GOOS=freebsd GOARCH=amd64 go build -ldflags="-s -w" -o tgpt-freebsd-amd64
                  GOOS=freebsd GOARCH=arm64 go build -ldflags="-s -w" -o tgpt-freebsd-arm64
                  GOOS=freebsd GOARCH=arm go build -ldflags="-s -w" -o tgpt-freebsd-arm
                  GOOS=freebsd GOARCH=386 go build -ldflags="-s -w" -o tgpt-freebsd-i386   

                  echo "## Changelog:" >> ${{ github.workspace }}-CHANGELOG.txt    

                  echo "<details><summary>SHA256 Hashes</summary><code>" >> ${{ github.workspace }}-CHANGELOG.txt      

                  echo "SHA256 hashes of the built binaries:"
                  echo "SHA256 hashes of the built binaries:" >> ${{ github.workspace }}-CHANGELOG.txt

                  sha256sum tgpt-linux-amd64 
                  sha256sum tgpt-linux-amd64 >> ${{ github.workspace }}-CHANGELOG.txt
                  
                  sha256sum tgpt-linux-i386
                  sha256sum tgpt-linux-i386 >> ${{ github.workspace }}-CHANGELOG.txt
                  
                  sha256sum tgpt-linux-arm64
                  sha256sum tgpt-linux-arm64 >> ${{ github.workspace }}-CHANGELOG.txt

                  sha256sum tgpt-linux-arm
                  sha256sum tgpt-linux-arm >> ${{ github.workspace }}-CHANGELOG.txt
                  
                  sha256sum tgpt-amd64.exe
                  sha256sum tgpt-amd64.exe >> ${{ github.workspace }}-CHANGELOG.txt
                  
                  sha256sum tgpt-i386.exe
                  sha256sum tgpt-i386.exe >> ${{ github.workspace }}-CHANGELOG.txt
                  
                  sha256sum tgpt-mac-amd64
                  sha256sum tgpt-mac-amd64 >> ${{ github.workspace }}-CHANGELOG.txt
                  
                  sha256sum tgpt-mac-arm64
                  sha256sum tgpt-mac-arm64 >> ${{ github.workspace }}-CHANGELOG.txt

                  echo "</code></details>" >> ${{ github.workspace }}-CHANGELOG.txt

            - name: Upload Artifacts
              id: upload-artifacts
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                      tgpt-linux-amd64
                      tgpt-linux-i386
                      tgpt-linux-arm64
                      tgpt-linux-arm
                      tgpt-amd64.exe
                      tgpt-i386.exe
                      tgpt-arm.exe
                      tgpt-arm64.exe
                      tgpt-mac-amd64
                      tgpt-mac-arm64
                      tgpt-netbsd-amd64
                      tgpt-netbsd-arm64
                      tgpt-netbsd-arm
                      tgpt-netbsd-i386
                      tgpt-freebsd-amd64
                      tgpt-freebsd-arm64
                      tgpt-freebsd-arm
                      tgpt-freebsd-i386  
                      tgpt-openbsd-amd64
                      tgpt-openbsd-arm64
                      tgpt-openbsd-arm
                      tgpt-openbsd-i386
                      
                  token: ${{ secrets.GITHUB_TOKEN }}
                  draft: true
                  tag_name: v
                  name: tgpt
                  body_path: ${{ github.workspace }}-CHANGELOG.txt

            - name: Run Unit Tests
              run: |
                  go test ./... -v

            - name: Code Coverage
              run: |
                  go test -coverprofile=coverage.out ./...
                  go tool cover -html=coverage.out -o coverage.html
              continue-on-error: true

            - name: Upload Coverage Report
              uses: actions/upload-artifact@v2
              with:
                  name: coverage-report
                  path: coverage.html

            - name: Deploy to Staging
              if: github.ref == 'refs/heads/release'
              run: |
                  echo "Deploying to staging environment..."
                  # Add your deployment script or commands here
                  # For example, you can use scp to copy files to a remote server
                  # scp tgpt-linux-amd64 user@staging-server:/path/to/deploy
                  # ssh user@staging-server 'systemctl restart tgpt-service'
